import hashlib
import secrets


def generate_session_token() -> str:
    """A session identifier from a cryptographic random source, long
    enough not to be guessable, and derived from nothing knowable --
    not the user's id, not a counter, not the creation time
    (session-management spec)."""
    return secrets.token_urlsafe(32)


def generate_state() -> str:
    """The unpredictable value that accompanies one authorization cycle
    (identity-provider spec, D3): the callback is rejected unless it
    presents this same value back."""
    return secrets.token_urlsafe(24)


def hash_session_token(token: str) -> str:
    """Fast digest of an opaque, high-entropy session token (D7).

    The token is generated by the system with a cryptographic random
    source, never guessed by a person -- there is nothing to make
    expensive by using a slow, password-oriented hash, and doing so
    would only add latency to every authenticated request, the hottest
    path in the system.
    """
    return hashlib.sha256(token.encode("ascii")).hexdigest()
