"""Keeps an explanation from delegating what it says to somewhere else.

An explanation written anywhere in this repository has to stand on its own.
Naming the document a decision was recorded in makes the reader open it to
understand a line, and that document is not always going to be within reach
of whoever is reading the code.

What counts as such a name is read from the planning directory at run time
-- the capability directories and the change directories -- rather than
listed here. A written list would go stale the same way the habit it forbids
does: the next change to be recorded would not be on it, and could be cited
with nothing to say so. Reading them means recording a change extends this
check by recording it. It also means this file holds none of the strings it
rejects, so it does not have to skip itself.

A capability's or a change's name is distinctive enough to look for in a
whole file. A numbered decision is not: it is one letter and a digit or two,
a credible thing to find in the path data of an inline drawing. That one is
looked for only in text that is actually a comment, which is why this file
knows how to pull the comments out of each kind of file it reads.

It lives in the suite rather than in a standalone script for the same reason
as the convention checks next to it: a script has to be remembered.
"""

import ast
import io
import re
import tokenize
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
_PLANNING = _REPO_ROOT / "openspec"

# Directories that hold decisions, text that is not the project's own, or
# files nobody edits by hand.
_SKIPPED_DIRS = frozenset(
    {
        "openspec",
        "local",
        ".claude",
        ".agents",
        ".git",
        ".codegraph",
        ".vscode",
        ".scratch",
        "node_modules",
        ".venv",
        "__pycache__",
        ".pytest_cache",
        ".ruff_cache",
        "dist",
        "build",
    }
)

_SKIPPED_FILES = frozenset(
    {
        "CLAUDE.md",
        # Written by a tool, from the packages it describes.
        "AGENTS.md",
        # Regenerated by dbmate on every migration.
        "schema.sql",
    }
)

_SCANNED_SUFFIXES = frozenset(
    {
        ".py",
        ".ts",
        ".tsx",
        ".js",
        ".jsx",
        ".yaml",
        ".yml",
        ".conf",
        ".template",
        ".sh",
        ".sql",
        ".md",
        ".html",
    }
)

# Files worth reading that carry no suffix of their own, or one that says
# nothing about how to read them.
_SCANNED_NAMES = frozenset({".env.example", "Dockerfile"})


def _scanned_files() -> list[Path]:
    found: list[Path] = []
    stack = [_REPO_ROOT]
    while stack:
        directory = stack.pop()
        for entry in directory.iterdir():
            if entry.is_dir():
                if entry.name not in _SKIPPED_DIRS:
                    stack.append(entry)
                continue
            if entry.name in _SKIPPED_FILES:
                continue
            if entry.suffix in _SCANNED_SUFFIXES or entry.name in _SCANNED_NAMES:
                found.append(entry)
    return sorted(found)


def _decision_document_names() -> list[str]:
    """Every name a line could cite: one per capability, one per change,
    recorded or still in flight. A change's directory carries the date it
    was recorded as a prefix, which is not part of its name."""
    names = {path.name for path in (_PLANNING / "specs").iterdir() if path.is_dir()}
    for path in (_PLANNING / "changes").iterdir():
        if not path.is_dir():
            continue
        if path.name == "archive":
            names.update(recorded.name for recorded in path.iterdir() if recorded.is_dir())
            continue
        names.add(path.name)
    return sorted(re.sub(r"^\d{4}-\d{2}-\d{2}-", "", name) for name in names)


def _line_of(text: str, index: int) -> int:
    return text.count("\n", 0, index) + 1


def _blank_out(text: str, pattern: str) -> str:
    """Replaces what `pattern` matches with spaces, keeping every newline
    where it was so a line number computed afterwards still holds."""

    def erase(match: re.Match[str]) -> str:
        return "".join("\n" if char == "\n" else " " for char in match.group(0))

    return re.sub(pattern, erase, text)


_TS_STRING = r"\"(?:\\.|[^\"\\\n])*\"|'(?:\\.|[^'\\\n])*'|`(?:\\.|[^`\\])*`"


def _python_comments(text: str) -> list[tuple[int, str]]:
    found: list[tuple[int, str]] = []
    try:
        for token in tokenize.generate_tokens(io.StringIO(text).readline):
            if token.type == tokenize.COMMENT:
                found.append((token.start[0], token.string))
    except (tokenize.TokenError, IndentationError, SyntaxError):
        pass
    try:
        tree = ast.parse(text)
    except SyntaxError:
        return found
    for node in ast.walk(tree):
        if not isinstance(node, ast.Module | ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
            continue
        doc = ast.get_docstring(node, clean=False)
        if doc is None:
            continue
        # The docstring's own node, for the line it starts on.
        first = node.body[0]
        found.append((getattr(first, "lineno", 1), doc))
    return found


def _c_style_comments(text: str) -> list[tuple[int, str]]:
    """Comments of a file whose strings can hold `//` -- a URL is the
    everyday case -- so the strings go first and what is left is comment
    or code."""
    stripped = _blank_out(text, _TS_STRING)
    found = [
        (_line_of(stripped, match.start()), match.group(0))
        for match in re.finditer(r"//[^\n]*|/\*[\s\S]*?\*/", stripped)
    ]
    return found


def _hash_comments(text: str) -> list[tuple[int, str]]:
    found = []
    for number, line in enumerate(text.splitlines(), start=1):
        marker = line.find("#")
        if marker == -1:
            continue
        if line[marker:].startswith("#!") and number == 1:
            continue
        found.append((number, line[marker:]))
    return found


def _sql_comments(text: str) -> list[tuple[int, str]]:
    return [
        (_line_of(text, match.start()), match.group(0))
        for match in re.finditer(r"--[^\n]*|/\*[\s\S]*?\*/", text)
    ]


def _whole_file(text: str) -> list[tuple[int, str]]:
    return [(1, text)]


def _comments_of(path: Path, text: str) -> list[tuple[int, str]]:
    if path.suffix == ".py":
        return _python_comments(text)
    if path.suffix in {".ts", ".tsx", ".js", ".jsx"}:
        return _c_style_comments(text)
    if path.suffix == ".sql":
        return _sql_comments(text)
    if path.suffix in {".md", ".html"}:
        # Every line of these is written to be read.
        return _whole_file(text)
    return _hash_comments(text)


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        return None


def test_a_string_that_looks_like_a_comment_is_not_read_as_one():
    """The case this costs the most to get wrong: an address carries
    `//` in the middle of a string, and reading it as a comment would
    report whatever follows it on that line."""
    source = 'const endpoint = "https://example.com/here";\n// a comment\n'
    assert _c_style_comments(source) == [(2, "// a comment")]

    assert _python_comments('x = "not a comment"\n# a comment\n') == [(2, "# a comment")]

    # A shebang is not an explanation of anything.
    assert _hash_comments("#!/bin/sh\n# a comment\n") == [(2, "# a comment")]


def test_a_comment_spanning_several_lines_is_read_whole():
    """Read line by line, a block comment would only ever be matched on
    the line its marker is on, and the rest would go unchecked."""
    line, comment = _c_style_comments("/* opens\n   continues\n   closes */\n")[0]
    assert line == 1
    assert "continues" in comment

    doc = _python_comments('"""Opens.\n\nContinues later.\n"""\n')[0][1]
    assert "Continues later." in doc


def test_no_explanation_names_the_document_its_decision_was_recorded_in():
    names = _decision_document_names()
    assert names, "no capability or change directories found; the check would pass vacuously"
    pattern = re.compile(
        r"(?<![\w-])(" + "|".join(re.escape(name) for name in names) + r")(?![\w-])"
    )
    offenders = []
    for path in _scanned_files():
        text = _read(path)
        if text is None:
            continue
        for match in pattern.finditer(text):
            offenders.append(
                f"  {path.relative_to(_REPO_ROOT).as_posix()}:{_line_of(text, match.start())}: "
                f"names {match.group(1)!r}"
            )
    assert not offenders, (
        "explanations that send the reader to a planning document; say what they need "
        "instead, and leave the reasoning where it is:\n" + "\n".join(offenders)
    )


# Citations that name no capability and no change, so the sweep above walks
# straight past them: a decision by its number, a task by its number, a
# planning file by its own filename, and one of their section headings.
_CITATION = re.compile(
    r"(?<![\w])(?:D\d+|tasks?\s+\d+\.\d+|design\.md|proposal|\(Risks[:)]|"
    r"(?:this|that|the)\s+change's)(?![\w])",
    re.IGNORECASE,
)


def test_no_comment_cites_a_numbered_decision():
    offenders = []
    for path in _scanned_files():
        text = _read(path)
        if text is None:
            continue
        for line, comment in _comments_of(path, text):
            for match in _CITATION.finditer(comment):
                # The line inside the comment, so a block reports where
                # the citation is and not where the block opens.
                at = line + _line_of(comment, match.start()) - 1
                offenders.append(
                    f"  {path.relative_to(_REPO_ROOT).as_posix()}:{at}: cites {match.group(0)!r}"
                )
    assert not offenders, (
        "comments citing a numbered decision; state what the line needs instead:\n"
        + "\n".join(offenders)
    )
