/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as ATokenRouteImport } from './routes/a.$token'
import { Route as AppAlbumsIndexRouteImport } from './routes/_app/albums/index'
import { Route as AppAlbumsAlbumIdRouteRouteImport } from './routes/_app/albums/$albumId/route'
import { Route as AppAlbumsNewRouteImport } from './routes/_app/albums/new'
import { Route as AppAlbumsAlbumIdIndexRouteImport } from './routes/_app/albums/$albumId/index'
import { Route as AppAlbumsAlbumIdSwipeRouteImport } from './routes/_app/albums/$albumId/swipe'
import { Route as AppAlbumsAlbumIdUploadRouteImport } from './routes/_app/albums/$albumId/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const ATokenRoute = ATokenRouteImport.update({
  id: '/a/$token',
  path: '/a/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlbumsIndexRoute = AppAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsAlbumIdRouteRoute = AppAlbumsAlbumIdRouteRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsNewRoute = AppAlbumsNewRouteImport.update({
  id: '/albums/new',
  path: '/albums/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAlbumsAlbumIdIndexRoute = AppAlbumsAlbumIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlbumsAlbumIdRouteRoute,
} as any)
const AppAlbumsAlbumIdSwipeRoute = AppAlbumsAlbumIdSwipeRouteImport.update({
  id: '/swipe',
  path: '/swipe',
  getParentRoute: () => AppAlbumsAlbumIdRouteRoute,
} as any)
const AppAlbumsAlbumIdUploadRoute = AppAlbumsAlbumIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppAlbumsAlbumIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/a/$token': typeof ATokenRoute
  '/albums/$albumId': typeof AppAlbumsAlbumIdRouteRouteWithChildren
  '/albums/new': typeof AppAlbumsNewRoute
  '/albums/': typeof AppAlbumsIndexRoute
  '/albums/$albumId/swipe': typeof AppAlbumsAlbumIdSwipeRoute
  '/albums/$albumId/upload': typeof AppAlbumsAlbumIdUploadRoute
  '/albums/$albumId/': typeof AppAlbumsAlbumIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/home': typeof AppHomeRoute
  '/a/$token': typeof ATokenRoute
  '/albums/new': typeof AppAlbumsNewRoute
  '/albums': typeof AppAlbumsIndexRoute
  '/albums/$albumId/swipe': typeof AppAlbumsAlbumIdSwipeRoute
  '/albums/$albumId/upload': typeof AppAlbumsAlbumIdUploadRoute
  '/albums/$albumId': typeof AppAlbumsAlbumIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/home': typeof AppHomeRoute
  '/a/$token': typeof ATokenRoute
  '/_app/albums/$albumId': typeof AppAlbumsAlbumIdRouteRouteWithChildren
  '/_app/albums/new': typeof AppAlbumsNewRoute
  '/_app/albums/': typeof AppAlbumsIndexRoute
  '/_app/albums/$albumId/swipe': typeof AppAlbumsAlbumIdSwipeRoute
  '/_app/albums/$albumId/upload': typeof AppAlbumsAlbumIdUploadRoute
  '/_app/albums/$albumId/': typeof AppAlbumsAlbumIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/home'
    | '/a/$token'
    | '/albums/$albumId'
    | '/albums/new'
    | '/albums/'
    | '/albums/$albumId/swipe'
    | '/albums/$albumId/upload'
    | '/albums/$albumId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/home'
    | '/a/$token'
    | '/albums/new'
    | '/albums'
    | '/albums/$albumId/swipe'
    | '/albums/$albumId/upload'
    | '/albums/$albumId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/home'
    | '/a/$token'
    | '/_app/albums/$albumId'
    | '/_app/albums/new'
    | '/_app/albums/'
    | '/_app/albums/$albumId/swipe'
    | '/_app/albums/$albumId/upload'
    | '/_app/albums/$albumId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ATokenRoute: typeof ATokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/a/$token': {
      id: '/a/$token'
      path: '/a/$token'
      fullPath: '/a/$token'
      preLoaderRoute: typeof ATokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/albums/': {
      id: '/_app/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AppAlbumsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/albums/$albumId': {
      id: '/_app/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AppAlbumsAlbumIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/albums/new': {
      id: '/_app/albums/new'
      path: '/albums/new'
      fullPath: '/albums/new'
      preLoaderRoute: typeof AppAlbumsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/albums/$albumId/': {
      id: '/_app/albums/$albumId/'
      path: '/'
      fullPath: '/albums/$albumId/'
      preLoaderRoute: typeof AppAlbumsAlbumIdIndexRouteImport
      parentRoute: typeof AppAlbumsAlbumIdRouteRoute
    }
    '/_app/albums/$albumId/swipe': {
      id: '/_app/albums/$albumId/swipe'
      path: '/swipe'
      fullPath: '/albums/$albumId/swipe'
      preLoaderRoute: typeof AppAlbumsAlbumIdSwipeRouteImport
      parentRoute: typeof AppAlbumsAlbumIdRouteRoute
    }
    '/_app/albums/$albumId/upload': {
      id: '/_app/albums/$albumId/upload'
      path: '/upload'
      fullPath: '/albums/$albumId/upload'
      preLoaderRoute: typeof AppAlbumsAlbumIdUploadRouteImport
      parentRoute: typeof AppAlbumsAlbumIdRouteRoute
    }
  }
}

interface AppAlbumsAlbumIdRouteRouteChildren {
  AppAlbumsAlbumIdSwipeRoute: typeof AppAlbumsAlbumIdSwipeRoute
  AppAlbumsAlbumIdUploadRoute: typeof AppAlbumsAlbumIdUploadRoute
  AppAlbumsAlbumIdIndexRoute: typeof AppAlbumsAlbumIdIndexRoute
}

const AppAlbumsAlbumIdRouteRouteChildren: AppAlbumsAlbumIdRouteRouteChildren = {
  AppAlbumsAlbumIdSwipeRoute: AppAlbumsAlbumIdSwipeRoute,
  AppAlbumsAlbumIdUploadRoute: AppAlbumsAlbumIdUploadRoute,
  AppAlbumsAlbumIdIndexRoute: AppAlbumsAlbumIdIndexRoute,
}

const AppAlbumsAlbumIdRouteRouteWithChildren =
  AppAlbumsAlbumIdRouteRoute._addFileChildren(
    AppAlbumsAlbumIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppAlbumsAlbumIdRouteRoute: typeof AppAlbumsAlbumIdRouteRouteWithChildren
  AppAlbumsNewRoute: typeof AppAlbumsNewRoute
  AppAlbumsIndexRoute: typeof AppAlbumsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppAlbumsAlbumIdRouteRoute: AppAlbumsAlbumIdRouteRouteWithChildren,
  AppAlbumsNewRoute: AppAlbumsNewRoute,
  AppAlbumsIndexRoute: AppAlbumsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ATokenRoute: ATokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
